In [1]:
import numpy as np

In [2]:
test_array = np.array([1, 4, 5, 8], float)
test_array

array([1., 4., 5., 8.])

넘파이 배열은 파이썬 리스트와 달리 모든 구성 요소에 값이 존재해야 함.

In [3]:
test_list = [[1, 4, 5, 8], [1, 4, 5]]
print(test_list)
print(type(test_list))

test_array = np.array(test_list, float)
print(test_array)
print(type(test_array))

[[1, 4, 5, 8], [1, 4, 5]]
<class 'list'>


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

동적 타이핑 지원 X

In [4]:
test_list = [1, 4, 5, 'DSU']
print(test_list)
print(type(test_list))

test_array = np.array(test_list)
print(test_array)
print(type(test_array))

[1, 4, 5, 'DSU']
<class 'list'>
['1' '4' '5' 'DSU']
<class 'numpy.ndarray'>


이 경우, float가 64비트라서, stride가 8바이트로 출력됨

In [5]:
test_array = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]], float)
print(type(test_array[0][0]))
print(test_array.dtype)
print(test_array.shape)
print(test_array.strides)

<class 'numpy.float64'>
float64
(3, 3)
(24, 8)


In [6]:
print(2+7)
print("2"+"7")
test_array = np.array([1, 4, 5, "8"], float)
print(test_array)
print(test_array.shape)

9
27
[1. 4. 5. 8.]
(4,)


In [7]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
matrix_arr = np.array(matrix, int)
tensor_rank3 = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
rank3_arr = np.array(tensor_rank3, int)

print(matrix_arr.shape)
print(matrix)
print(matrix_arr)
print(rank3_arr.shape)
print(rank3_arr)

(3, 4)
[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
[[1 2 5 8]
 [1 2 5 8]
 [1 2 5 8]]
(4, 3, 4)
[[[1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]]

 [[1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]]

 [[1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]]

 [[1 2 5 8]
  [1 2 5 8]
  [1 2 5 8]]]


reshape로 재구성 가능

In [46]:
x = np.arange(8)
print(x, "\n")
print(x.reshape(2,-1), "\n")
print(x.reshape(2,2,-1), "\n")

[0 1 2 3 4 5 6 7] 

[[0 1 2 3]
 [4 5 6 7]] 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 



인덱싱

In [73]:
x = np.arange(6).reshape(2,-1)
print(x)
print(x[0][0])
print(x[0, 2])
x[0, 1] = 100
print(x)

[[0 1 2]
 [3 4 5]]
0
2
[[  0 100   2]
 [  3   4   5]]


슬라이싱

In [35]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
print(x, "\n")
print(x[:,2:], "\n")    # 전체 행의 2열 이상
print(x[1,1:3], "\n")   # 1행의 1~2열
print(x[1:3])           # 1~2행의 전체   

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

[[ 3  4  5]
 [ 8  9 10]] 

[7 8] 

[[ 6  7  8  9 10]]


스텝 [시작 인덱스 : 마지막 인덱스 : 증가값]

In [39]:
x = np.array(range(15), int).reshape(3, -1)
print(x, "\n")
print(x[:,::2], "\n")
print(x[::2,::3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]] 

[[ 0  3]
 [10 13]]


배열 생성 함수

In [49]:
print(np.arange(10))
print(np.arange(-5,5))
print(np.arange(0,5,0.5))

[0 1 2 3 4 5 6 7 8 9]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [68]:
print("ones\n", np.ones(shape=(5,2), dtype=np.int8), "\n")      # ones = 1로 구성된 배열 생성
print("zeros\n", np.zeros(shape=(2,2), dtype=np.float32), "\n")  # zeros = 0으로 구성된 배열 생성
print("empty\n", np.empty(shape=(2,4), dtype=np.float32))        # empty = 메모리 공간을 확보

ones
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]] 

zeros
 [[0. 0.]
 [0. 0.]] 

empty
 [[0.     1.875  0.     2.25  ]
 [0.     2.3125 0.     2.5   ]]


In [67]:
print("identity\n", np.identity(n=3, dtype=int), "\n")  # identity = 단위행렬 생성
print("eye\n", np.eye(3,5,2, dtype=int), "\n")     # eye = 시작점의 행렬과 크기 지정 가능
matrix = np.arange(9).reshape(3,3)        # diag = 특정 값에서 대각 행렬 추출
print(matrix, "\n")
print("diag\n", np.diag(matrix))

identity
 [[1 0 0]
 [0 1 0]
 [0 0 1]] 

eye
 [[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

diag
 [0 4 8]


통계 분석 함수

In [72]:
print("uniform\n", np.random.uniform(0,5,10), "\n")    # uniform = 균등분포 (시작값, 끝값, 데이터개수)
print("normal\n", np.random.normal(0,2,10))            # normal = 정규분포 (평균값, 끝값, 데이터개수)

uniform
 [0.44236341 2.34485384 3.49244605 2.09933891 2.14896327 3.3443931
 3.99999877 3.13876699 0.18307027 2.71019145] 

normal
 [-2.11114012  1.01689169 -0.31978515 -2.0395899   1.62687497 -1.92266881
 -0.20890197 -1.03250651  4.34572335 -3.16768055]


연산함수

In [77]:
test_array = np.arange(1,11)
print(test_array)
print(test_array.sum())

[ 1  2  3  4  5  6  7  8  9 10]
55


In [84]:
test_array = np.arange(1,13).reshape(3,4)
print(test_array)
print("axis = 0\n", test_array.sum(axis=0))  # 동일 행을 덧셈
print("axis = 1\n", test_array.sum(axis=1))  # 동일 열을 덧셈

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
axis = 0
 [15 18 21 24]
axis = 1
 [10 26 42]


In [83]:
test_array = np.arange(1,13).reshape(3,4)
third_order_tensor = np.array([test_array,test_array,test_array])
print(third_order_tensor, "\n")
print("axis = 0\n", third_order_tensor.sum(axis=0),"\n")
print("axis = 1\n", third_order_tensor.sum(axis=1),"\n")
print("axis = 2\n", third_order_tensor.sum(axis=2),"\n")

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]] 

axis = 0
 [[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]] 

axis = 1
 [[15 18 21 24]
 [15 18 21 24]
 [15 18 21 24]] 

axis = 2
 [[10 26 42]
 [10 26 42]
 [10 26 42]] 

